### ISSUE TITLE
reddit stuff

### ISSUE THREAD

**Issue by gachiemchiep** [gachiemchiep/source_code#1]
Hello @3dsf 
Let's discuss here. 
Would you mind write down detail in this issue. Thanks

**Comment by 3dsf** [comment]
Hi,
I've picked up some some hardware that I think would be good for computer vision / machine learning problems :
- computer with w/ rtx2060s
- jetson nano
- l515 camera
- d435i camera

I've used linux for many years, and with conda I am able to run different machine learning / computer vision repos; I'm familiar with troubleshooting, and like researching paths to solve problems.
I like depth maps, but do not need to limit my self to this area.  
After reading one of your comments on reddit, I thought you would be a good person to ask about what direction I should pursue for learning, and what type of opportunities I could pursue with industrial clients.  

I also have started using machine learning / computer vision for art projects and will be using it to improve the viewers experience.  

Thanks,
3dsf

**Comment by gachiemchiep** [comment]
Hello @3dsf 
Bin picking is a famous problem in the robotics industry. There're some commercial products available in the market. Here's an example of bin-picking. This video will give a draft about what is "bin-picking".  
[solomon 3d bin picking](https://www.youtube.com/watch?v=7PqQa_LfhgE&ab_channel=HumaRobotics)

The direction for learning is reading research paper and trying some example code. 
1. Reading : find and read some survey about "bin-picking", "robot-grasping", "6 dof pose estimation". You can find some master thesis on the Internet about "bin-picking". For [example](https://core.ac.uk/download/pdf/196657181.pdf). 
2. Code : try [OpenCV surface mathcing](https://docs.opencv.org/master/d9/d25/group__surface__matching.html) or [PCL Cluster Recognition and 6DOF Pose Estimation using VFH descriptors](https://pcl.readthedocs.io/projects/tutorials/en/master/vfh_recognition.html#vfh-recognition)

**what type of opportunities I could pursue with industrial clients.** : this field is a red-ocean full of sharks. As an engineer, it will help you find a job easier but as a business owner, I don't think any self-developed product could win against the commercial products.

**Comment by 3dsf** [comment]
thanks @gachiemchiep 
I'm still in the gravel of stream somewhere.  I'll keep your words in mind and study the famous problems.
